import { toast } from 'sonner';
import { useAppStatusStore } from '../stores/app-status';
import { AlertCircle } from './icons';

const SOUNDCLOUD_BAN_TOAST_ID = 'soundcloud-app-ban';
const SOUNDCLOUD_BAN_MESSAGE = 'Приложение забанено саундклаудом. Подождите пока сделаю ротацию';

interface ErrorPayload {
  error?: string;
  message?: string;
}

function parseErrorPayload(body: string): ErrorPayload | null {
  try {
    return JSON.parse(body) as ErrorPayload;
  } catch {
    return null;
  }
}

export function isSoundCloudAppBan(status: number, body: string) {
  if (status !== 403) {
    return false;
  }

  const payload = parseErrorPayload(body);
  const error = payload?.error?.toLowerCase() ?? '';
  const message = payload?.message?.toLowerCase() ?? body.toLowerCase();

  return (
    error.includes('soundcloud api error') &&
    (message.includes('request blocked') ||
      message.includes('the request could not be satisfied') ||
      message.includes('generated by cloudfront'))
  );
}

export function showSoundCloudAppBanToast() {
  useAppStatusStore.getState().setSoundcloudBlocked(true);
  toast.custom(
    () => (
      <div className="relative w-[380px] overflow-hidden rounded-[28px] border border-white/14 bg-[linear-gradient(180deg,rgba(255,255,255,0.16),rgba(255,255,255,0.06))] p-1 shadow-[0_20px_60px_rgba(0,0,0,0.45),0_0_40px_rgba(255,85,0,0.12)] backdrop-blur-[36px]">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.22),transparent_36%),radial-gradient(circle_at_bottom_right,rgba(255,85,0,0.16),transparent_34%)]" />
        <div className="relative flex items-start gap-3 rounded-[24px] border border-white/8 bg-black/28 px-4 py-4">
          <div className="mt-0.5 flex size-11 shrink-0 items-center justify-center rounded-[16px] border border-white/12 bg-white/10 shadow-[inset_0_1px_0_rgba(255,255,255,0.12),0_0_25px_rgba(255,85,0,0.18)]">
            <AlertCircle size={18} className="text-accent" strokeWidth={2} />
          </div>
          <div className="min-w-0">
            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-white/45">
              SoundCloud block
            </div>
            <div className="mt-1 text-[15px] font-semibold leading-5 text-white/92">
              {SOUNDCLOUD_BAN_MESSAGE}
            </div>
          </div>
        </div>
      </div>
    ),
    {
      id: SOUNDCLOUD_BAN_TOAST_ID,
      duration: 12000,
    },
  );
}
